_target_: stable_worldmodel.solver.GradientSolver
model: ???
n_steps: 30
batch_size: 1
num_samples: 100
action_noise: 0
device: "cuda"
seed: ${seed}
optimizer_cls:
  _target_: hydra.utils.get_class
  path: torch.optim.AdamW
optimizer_kwargs:
  lr: 0.1