defaults:
  - _self_
  - data: ogb

output_model_name: lewm
subdir: ${hydra:job.id}

hydra:
  run:
    dir: ${oc.env:HOME}/.stable-wm/${subdir}/hydra

num_workers: 2
train_split: 0.9
split_seed: 3072
seed: 3072
img_size: 224
patch_size: 14
encoder_scale: tiny
dump_object: True

trainer:
  max_epochs: 10
  devices: auto
  accelerator: gpu
  precision: bf16
  gradient_clip_val: 1.0
  default_root_dir: ${oc.env:HOME}/.stable-wm/${subdir}

loader:
  batch_size: 128
  num_workers: ${num_workers}
  persistent_workers: False
  prefetch_factor: 3
  pin_memory: False

optimizer:
  type: AdamW
  lr: 5e-5
  weight_decay: 1e-3

wandb:
  enabled: False
  config:
    entity: lewm
    project: lewm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False

wm:
  type: lewm
  history_size: 3
  num_preds: 1
  embed_dim: 192

predictor:
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0

loss:
  sigreg:
    weight: 0.0 #0.09,0.001
    kwargs:
      knots: 17
      num_proj: 1024
  state_align:
    weight: 1.
    hidden_dim: 256
    supervised_indices: ${data.state_alignment.supervised_indices}
    velocity_indices: ${data.state_alignment.velocity_indices}
  idm:
    weight: 1.
    hidden_dim: 512
