defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/OGBCube-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: ??? # make sure it's >= eval_budget
  history_size: 1
  frame_skip: 1
  env_type: single
  ob_type: states
  multiview: False
  width: 224
  height: 224
  visualize_info: False
  terminate_at_goal: True

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action

seed: 42
policy: random # ckpt name or random

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5 # frameskip

# evaluation from dataset (replay expert trajectories)
eval:
  num_eval: 50
  goal_offset_steps: 25
  eval_budget: 50
  img_size: 224
  dataset_name: ogbench/cube_single_expert
  callables:
    # -- set state
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel
    # -- set target pos
    - method: set_target_pos
      args:
        cube_id:
          value: 0
          in_dataset: False
        target_pos:
          value: goal_privileged_block_0_pos
        target_quat:
          value: goal_privileged_block_0_quat

output:
  filename: ogb_cube_results.txt
