defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/ReacherDMControl-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: ??? # make sure it's >= eval_budget
  history_size: 1
  frame_skip: 1
  task: qpos_match

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action

seed: 42
policy: random # ckpt name or random

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5 # frameskip

# evaluation from dataset (replay expert trajectories)
eval:
  num_eval: 50
  goal_offset_steps: 25
  eval_budget: 50
  img_size: 224
  dataset_name: dmc/reacher_random
  callables:
    # -- set state
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel

    - method: set_target_qpos
      args:
        target_qpos:
          value: goal_qpos

output:
  filename: dmc_results.txt
