defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/TwoRoom-v1
  num_envs: ${eval.num_eval}
  max_episode_steps: ??? # make sure it's >= eval_budget
  history_size: 1
  frame_skip: 1

seed: 42
policy: random # ckpt name or random

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action
    - proprio

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5 # frameskip

# evaluation from dataset (replay expert trajectories)
eval:
  num_eval: 50
  goal_offset_steps: 25
  eval_budget: 50
  img_size: 224
  dataset_name: tworoom
  callables:
    # -- set state
    - method: _set_state
      args:
        state:
          value: proprio
    # -- set goal state
    - method: _set_goal_state
      args:
        goal_state:
          value: goal_proprio

output:
  filename: tworoom_results.txt